/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform.createUser;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Calendar;
import javax.swing.*;
import loginform.Login;
import loginform.guestDatabaseConn;
/**
 *
 * @author vatsalpatel
 */
public class CreateUserFrame extends javax.swing.JFrame {
    Connection connection;
    /**
     * Creates new form LoginFrame2
     */
    public CreateUserFrame() {
        initComponents();
        connection = guestDatabaseConn.dbConnection();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName = new javax.swing.JTextField();
        rName = new javax.swing.JTextField();
        setPassword = new javax.swing.JTextField();
        creatAccount = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userName.setForeground(new java.awt.Color(153, 153, 153));
        userName.setText("USERNAME");
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        rName.setForeground(new java.awt.Color(153, 153, 153));
        rName.setText("NAME");
        rName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rNameFocusLost(evt);
            }
        });
        rName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNameActionPerformed(evt);
            }
        });

        setPassword.setForeground(new java.awt.Color(153, 153, 153));
        setPassword.setText("PASSWORD");
        setPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                setPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                setPasswordFocusLost(evt);
            }
        });
        setPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPasswordActionPerformed(evt);
            }
        });

        creatAccount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        creatAccount.setText("SUBMIT");
        creatAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatAccountActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creatAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rName, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(rName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(setPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creatAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void rNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNameActionPerformed

    private void setPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setPasswordActionPerformed

    private void rNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rNameFocusGained
        if(rName.getText().equals("NAME")){
            rName.setText("");
            rName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_rNameFocusGained

    private void rNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rNameFocusLost
        if(rName.getText().equals("")){
            rName.setText("NAME");
            rName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rNameFocusLost

    private void userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusGained
        if(userName.getText().equals("USERNAME")){
            userName.setText("");
            userName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_userNameFocusGained

    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
        if(userName.getText().equals("")){
            userName.setText("USERNAME");
            userName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_userNameFocusLost

    private void setPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_setPasswordFocusGained
        if(setPassword.getText().equals("PASSWORD")){
            setPassword.setText("");
            setPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_setPasswordFocusGained

    private void setPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_setPasswordFocusLost
        if(setPassword.getText().equals("")){
            setPassword.setText("PASSWORD");
            setPassword.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_setPasswordFocusLost

    private void creatAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatAccountActionPerformed
        createUser();
    }//GEN-LAST:event_creatAccountActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        goBackFrame();   
    }//GEN-LAST:event_backBtnActionPerformed

    private void createUser(){
        try{
            Calendar calendar = Calendar.getInstance();
            java.sql.Date date = new java.sql.Date(calendar.getTime().getTime());
            String query = "INSERT INTO 'login' (userName, Password, Name, date)values(?, ?, ?, ?)";   
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, userName.getText());
            pst.setString(2, setPassword.getText());
            pst.setString(3, rName.getText());
            pst.setDate(4, date);
            int n1 = pst.executeUpdate();
            if(n1>0){
                JOptionPane.showMessageDialog(null, "Susscess!");
                goBackFrame();
            }     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public void goBackFrame(){
        close();
        Login oldLogin = new Login();
        oldLogin.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton creatAccount;
    private javax.swing.JTextField rName;
    private javax.swing.JTextField setPassword;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
